const appConstants = require('./app');

module.exports = {
	MONGODB_CONNECTED : 'Connected to MongoDB successfully',
	MONGODB_CONNECTION_ERROR : 'Error in MongoDB connection',
	MONGODB_DISCONNECTED : 'Disconnected from MongoDB',
	MONGODB_DISCONNECTED_ON_PROCESS_TERMINATION : 'MongoDB disconnected on process termination',
	REQUIRES_ELEVATED_PRIVILEGES : ' Requires elevated privileges',
	ALREADY_IN_USE : ' is already in use',
	SERVER_RUNNING : 'Server running  on ',
	NO_RIGHTS_TO_UPDATE: 'You have no rights to modify',
	NO_RIGHTS_TO_UPDATE_COURSE_STATUS: 'You have no rights to update course status',
	INTERNAL_SERVER_ERROR : 'Internal server error',
	USER_DETAIL_FOUND:'User details found for user',
	PROBLEM_OCCURED :'Problem occurred',
	INVALID_CREDENTIAL:'Invalid credentials',
	EMAIL_NOT_VERIFIED:'Email not verified',
	GET_ALL_DATA_CATEGORY:'Get all data of category',
	NO_CATEGORY_FOUND:'No category found ',
	GET_OBJECT_AND_STORE:'Get object and store into',
	CATEGORY_DATA_NOT_FOUND:'CategoryData not found',
	INVALID_INPUTS:'Invalid inputs received...!',
	CATEGORY_SUCCESSFULLY_SAVED:'Category successfully saved ',
	CATEGORY_SUCCESSFULLY_UPDATED:'Category successfully updated ',
	FIll_ALL_BLANK_FIELD :'Please fill all required fields',
	CATEGORY_ALREADY_EXIST : 'Category already exist',
	CATEGORY_NOT_SAVED : 'Category not saved',
	CATEGORY_NOT_UPDATED : 'Category not updated',
	DATA_DELETED_FROM_CATEGORY: 'Data deleted from category',
	CATEGORY_SUCCESSFULLY_DELETED : 'Category successfully deleted',
	CATEGORY_DATA_NOT_FOUND: 'CategoryData not found',
	GET_ALL_DATA_SUBCATEGORY:'Get all data of subcategory',
	NO_SUBCATEGORY_FOUND:'No subcategory found ',
	SUBCATEGORY_DATA_NOT_FOUND:'SubcategoryData not found',
	SUBCATEGORY_SUCCESSFULLY_SAVED:'Subcategory successfully saved ',
	SUBCATEGORY_SUCCESSFULLY_UPDATED:'Subcategory successfully updated ',
	SUBCATEGORY_ALREADY_EXIST : 'Subcategory already exist',
	SUBCATEGORY_NOT_SAVED : 'Subcategory not saved',
	SUBCATEGORY_NOT_UPDATED : 'Subcategory not updated',
	DATA_DELETED_FROM_SUBCATEGORY: 'Data deleted from Subcategory',
	SUBCATEGORY_SUCCESSFULLY_DELETED : 'Subcategory successfully deleted',
	SUBCATEGORY_DATA_NOT_FOUND: 'SubcategoryData not found',
	NO_COURSE_FOUND :'Course not found',
	GET_ALL_DATA_COURSES:'Get all data of courses',
	USER_MENUS_SUCCESS:'Sending navigation menus for user',
	USER_MENUS_ERROR:'Problem occurred in finding navigation menus for user',
	USER_MENUS_NOT_FOUND:'Navigation menus not found for user',
	GET_OBJECT_AND_STORE_COURSE:'Get object and store course',
	COURSE_DATA_NOT_FOUND : 'CourseData not found',
	COURSE_SUCCESSFULLY_SAVED : 'Course successfully saved',
	COURSE_NOT_SAVED : 'Course not saved',
	DATA_DELETED_FROM_COURSE : 'Data deleted from Course',
	COURSE_DATA_NOT_FOUND : 'Course data not found',
	COURSE_SUCCESSFULLY_DELETED : 'Course successfully deleted',
	COURSE_NOT_UPDATED : 'Course not updated',
	COURSE_SUCCESSFULLY_UPDATED : 'Course successfully updated',
	COURSE_STATUS_UPDATED_SUCCESSFULLY : 'Course status updated successfully',
	COURSE_NOT_FOUND_FOR_THIS_TOPIC: 'Course not found for this topic',
	COURSE_STATUS_NOT_FOUND:'course status not found',
	TOPIC_NOT_SAVED : 'Topic not saved',
	TOPIC_SUCCESSFULLY_SAVED :'Topic successfully saved',
	USER_ROLE:'Sending user role for user',
	USER_ROLE_NOT_FOUND:'Unauthrozed access. User role not found for user',
	AUTHORIZATION_STARTED:'Authorization started by getting token from http request',
	NO_TOKEN : 'No token provided',
	VALID_TOKEN : 'Valid token provided',
	INVALID_TOKEN : 'Invalid token provided',
  TOKEN_NOT_REFRESHED: 'Token not refreshed since not platform type present in headers',
  GET_OBJECT_AND_STORE_TOPIC : 'Get object and store topic',
  TOPIC_DATA_NOT_FOUND:'Topic data not found',
  TOPIC_SUCCESSFULLY_SAVED: 'Topic successfully saved',
  TOPIC_ID_NOT_SAVED_IN_COURSE:'Topic id not saved in Course',
  GET_ID_AND_STORE : 'Get id and store',
  GET_COURSE_DATA_BY_ID : 'Get course data by id',
  TOPIC_SUCCESSFULLY_UPDATED : 'Topic successfully updated',
  TOPIC_NOT_UPDATED : 'Topic not updated',
  DATA_DELETED_FROM_TOPIC : 'Delete data from topic',
  TOPIC_SUCCESSFULLY_DELETED : 'Topic successfully deleted',
  TOPIC_DETAIL_FOUND : 'Topic detail found',
  TOPIC_NOT_FOUND_FOR_THIS_SUBTOPIC : 'Topic not found for this subtopic',
  SUBTOPIC_NOT_SAVED : 'Subtopic not saved',
  SUBTOPIC_SUCCESSFULLY_SAVED : 'Subtopic successfully saved',
  LEARNING_DATA_NOT_FOUND : 'Learning data not found',
  LEARNING_DATA_SUCCESSFULLY_UPDATED : 'Learning data is successfully updated',
  LEARNING_DATA_NOT_UPDATED : 'Learning data not updated',
  LEARNING_DATA_SUCCESSFULLY_UPDATED : 'Learning data successfully updated',
  LEANING_DATA_DELETED_FROM_SUBTOPIC : 'Learning data deleted from subtopics',
  LEARNING_DATA_SUCCESSFULLY_DELETED : 'Learning data successfully deleted',
  LEARNING_DATA_NOT_DELETED : 'Learning data not deleted',
  ORDER_NOT_CHANGE_OF_LEARNING_DATA : 'Order not change of learning data',
  SUCCESSFULLY_ORDER_CHANGE_OF_LEARNING_DATA: 'successfully order change of learning data',
  GET_SUBTOPIC_DATA_SUCCESSFULLY : 'Get subtopic data successfully',
  GET_OBJECT_AND_STORE_SUBTOPIC : 'Get object and store subtopic',
  SUBTOPIC_DATA_NOT_FOUND : 'Subtopic data not found for this id',
  SUBTOPIC_SUCCESSFULLY_DELETED : 'Subtopic successfully deleted',
  DATA_DELETED_FROM_SUBTOPIC : 'Data deleted from subtopic',
  SUBTOPIC_SUCCESSFULLY_UPDATED :'Subtopic successfully updated',
  SUBTOPIC_NOT_UPDATED : 'Subtopic not updated',
  GET_OBJECT_AND_STORE_SUBTOPICSDATA :'Get object and store SUBTOPICSdata',
  SUBTOPICSDATA_NOT_FOUND :'SUBTOPICSData not found',
  SUBTOPICSDATA_SUCCESSFULLY_SAVED : 'SUBTOPICS Data is successfully saved',
  SUBTOPICSITEM_SUCCESSFULLY_SAVED: 'SUBTOPICS item is successfully saved',
  DATA_DELETED_FROM_SUBTOPICS : 'Data Deleted from SUBTOPICS',
  DATA_SUCCESSFULLY_UPDATED : 'Data successfully updated',
  GET_PARAMETER_VALUE_AND_STORE_INTO : 'Get parameter value and store into',
  PLAYLIST_DATA_NOT_FOUND: 'Playlist Data not found',
  PLAYLIST_NOT_UPDATED : 'Playlist not updated',
  PLAYLIST_SUCCESSFULLY_DELETED : 'Playlist successfully deleted',
  PLAYLIST_SUCCESSFULLY_UPDATED : 'Playlist successfully updated',
  PLAYLIST_SUCCESSFULLY_SAVED : 'Playlist successfully saved',
  PLAYLIST_DATA_NOT_SAVED : 'Playlist not saved',
  PLAYLIST_DATA_FOUND : 'Playlist data found',
  PLAYLIST_DATA_NOT_FOUND: 'Playlist Data not found',
  PlAYLIST_NOTES_SUCCESSFULLY_SAVED : 'Playlist notes successfully saved',
  NOTES_DATA_NOT_FOUND : 'Notes data not found',
  SUBTOPICS_NOTES_NOT_SAVED : 'SUBTOPICS notes not saved',
  NOTES_ID_NOT_SAVED_IN_SUBTOPICS: 'Notes Id not saved in SUBTOPICS',
  DATA_DELETED_FROM_NOTES : 'Data deleted from notes',
  NOTES_DATA_NOT_FOUND : 'Notes data not found',
  NOTES_SUCCESSFULLY_DELETED : 'Notes successfully deleted',
  NOTES_DATA_NOT_FOUND : 'Notes data not found',
  NOTES_SUCCESSFULLY_UPDATED : 'Notes successfully updated',
  NOTES_NOT_UPDATED : 'Notes not updated',
  NOTES_SUCCESSFULLY_UPDATED : 'Notes successfully updated',
  ERROR_OCCURED_WHILE_DELETING_NOTES_FROM_SUBTOPICS :'error occured while deleting notes from SUBTOPICS',
  SUBTOPICS_REFERENCES_SUCCESSFULLY_SAVED : 'SUBTOPICS References successfully saved',
  REFERENCES_DATA_NOT_FOUND : 'References data not found',
  SUBTOPICS_REFERENCES_NOT_SAVED : 'SUBTOPICS References not saved',
  REFERENCES_ID_NOT_SAVED_IN_SUBTOPICS: 'References Id not saved in SUBTOPICS',
  DATA_DELETED_FROM_REFERENCES : 'Data deleted from References',
  REFERENCES_DATA_NOT_FOUND : 'References data not found',
  REFERENCES_SUCCESSFULLY_DELETED : 'References successfully deleted',
  REFERENCES_DATA_NOT_FOUND : 'References data not found',
  REFERENCES_SUCCESSFULLY_UPDATED : 'References successfully updated',
  REFERENCES_NOT_UPDATED : 'References not updated',
  REFERENCES_SUCCESSFULLY_UPDATED : 'References successfully updated',
  ERROR_OCCURED_WHILE_DELETING_REFERENCES_FROM_SUBTOPICS :'error occured while deleting references from SUBTOPICS',
  SUBTOPICS_KEYPOINTS_SUCCESSFULLY_SAVED : 'SUBTOPICS keypoints successfully saved',
  KEYPOINTS_DATA_NOT_FOUND : 'KEYPOINTS data not found',
  SUBTOPICS_KEYPOINTS_NOT_SAVED : 'SUBTOPICS keypoints not saved',
  KEYPOINTS_ID_NOT_SAVED_IN_SUBTOPICS: 'KEYPOINTS Id not saved in SUBTOPICS',
  DATA_DELETED_FROM_KEYPOINTS : 'Data deleted from keypoints',
  KEYPOINTS_DATA_NOT_FOUND : 'KEYPOINTS data not found',
  KEYPOINTS_SUCCESSFULLY_DELETED : 'KEYPOINTS successfully deleted',
  KEYPOINTS_DATA_NOT_FOUND : 'KEYPOINTS data not found',
  KEYPOINTS_SUCCESSFULLY_UPDATED : 'KEYPOINTS successfully updated',
  KEYPOINTS_NOT_UPDATED : 'KEYPOINTS not updated',
  KEYPOINTS_SUCCESSFULLY_UPDATED : 'KEYPOINTS successfully updated',
  SUBTOPICS_MEDIAFILES_NOT_SAVED : 'SUBTOPICS media Files not saved',
  SUBTOPICS_MEDIAFILES_SAVED :'SUBTOPICS media files successfully saved',
  MEDIA_ID_NOT_SAVED_IN_SUBTOPICS: 'Media files Id not saved in SUBTOPICS',
  FILE_UPLOAD_STORAGE_PROBLEM : 'File upload storage problem',
  DATA_DELETED_FROM_MEDIA : 'Data deleted from media',
  MEDIA_DATA_NOT_FOUND : 'Media data not found',
  ERROR_OCCURED_WHILE_DELETING_MEDIA_FROM_SUBTOPICS : 'error occured while deleting media from SUBTOPICS',
  MEDIA_SUCCESSFULLY_DELETED : 'Media successfully deleted',
  FILE_DELETE_FROM_STORAGE_ERROR : 'Error while deleting file from storage ',
  DATA_DELETED_FROM_MEDIA : 'Media data deleted from SUBTOPICS',
  REFRESH_TOKEN : 'Token refreshed',
  UNAUTHORIZED_ACCESS : 'Unauthrozed user access',
  NO_CATEGORIES_FOUND : 'Invalid input: expect categories to get subcategories',
  GET_DATA_SUCCESSFULLY : 'data get successfully',
  NO_SUBCATEGORIES_FOUND : 'Invalid input: expect subcategories to get courses',
  MISSING_EXPECTED_INPUT : "Expected input was not present",
  NO_DATA_FOUND : "No data found",
  SUBTOPICS_VIDEO_SUCCESSFULLY_SAVED: 'SUBTOPICS video successfully saved',
  SUBTOPICS_VIDEO_NOT_SAVED : 'SUBTOPICS video not saved',
  VIDEO_ID_NOT_SAVED_IN_SUBTOPICS : 'Video id not saved in SUBTOPICS',
  VIDEO_TOC_ADDED_SUCCESSFULLY: 'Video TOC added successfully',
  INPUT_NOT_PASSED:'input not passed',
  GET_VIDEO_AND_ADD_TOC_DATA:'Get Video content and add toc data',
  VIDEO_TOC_NOT_ADDED: 'Video toc not added',
  VIDEO_TOC_ADDED_SUCCESSFULLY:'Video toc added successfully',
  VIDEO_DELETED_FROM_SUBTOPICS :'Video deleted from SUBTOPICS',
  VIDEO_SUCCESSFULLY_DELETED: 'Video successfully deleted',
  ERROR_OCCURED_WHILE_DELETING_VIDEO_FROM_SUBTOPICS : 'error occured while deleting video from SUBTOPICS',
  VIDEO_DATA_NOT_FOUND : 'Video data not found',
  TOC_DELETED_FROM_VIDEO : 'Toc deleted from video',
  ERROR_OCCURED_WHILE_DELETING_TOC_FROM_VIDEO :'Error occurred while deleting toc from video',
  TOC_SUCCESSFULLY_DELETED : 'Toc successfully deleted',
  TOC_UPDATED_FROM_VIDEO : 'Toc updated from video',
  TOC_DATA_NOT_FOUND : 'Toc data not found',
  ERROR_OCCURED_WHILE_UPDATING_TOC_FROM_VIDEO :'Error occurred while updating toc from video',
  TOC_SUCCESSFULLY_UPDATED : 'Toc successfully updated',
  VIDEO_SEARCH_SUCCESS : 'Video search request completeled successfully',
  Action_DATA_NOT_FOUND: 'Action data not found',
  Action_DATA_NOT_UPDATED: 'Action data not updated',

  TOPIC_SOLUTION_NOT_SAVED : 'TOPICS media Files not saved',
  TOPIC_SOLUTION_SAVED :'TOPICS media files successfully saved',
  FILE_UPLOAD_STORAGE_PROBLEM : 'File upload storage problem',
  DATA_DELETED_FROM_SOLUTIONS : 'Data deleted from solution',
  SOLUTION_DATA_NOT_FOUND : 'solution data not found',
  SOLUTION_SUCCESSFULLY_DELETED : 'solution successfully deleted',
  FILE_DELETE_FROM_STORAGE_ERROR : 'Error while deleting file from storage ',
  ERROR_OCCURED_WHILE_DELETING_SOLUTION_FROM_TOPICS: 'Error occurred while deleting solutions from topics',

  ERROR_OCCURED_WHILE_DELETING_SUBTOPICS_FROM_TOPIC: 'Error occurred while deleting Subtopic from topic',

  FILE_TYPE_ERROR:'File type should be jpeg, jpg, & png',
  FILE_SIZE_ERROR:'File size should be less than 256kb',
  BAD_REQUEST: 'Bad request',

  BASICPROFILE : {
    PROFILE_PICTURE_SUCCESSFULLY_UPDATED:'Profile picture is successfully updated',
    INTERNAL_ERROR : 'Internal error occurred',
    FILE_UPLOAD_STORAGE_PROBLEM : 'File upload storage problem',
    PROBLEM_OCCURED :'Problem occurred',
    UPDATE_PROFILE_DATA_OF_USER:'updateProfile data of user',
    PROFILE_IS_SUCCESSFULLY_UPDATED : 'profile is successfully updated',
    FIll_ALL_BLANK_FIELD: 'Fill all blank field',
    FILE_TYPE_ERROR:'File type should be jpeg, jpg, & png',
    FILE_SIZE_ERROR:'File size should be less than 128kb',
    ADDRESS_IS_SUCCESSFULLY_UPDATED: 'address is successfully updated',
    SOCAILPROFILE_IS_SUCCESSFULLY_UPDATED: 'socail profile is successfully added',
    ACADEMIC_IS_SUCCESSFULLY_UPDATED: 'academic details is successfully updated',
    SOCAILPROFILEURL_IS_SUCCESSFULLY_UPDATED: 'socail profile url is successfully updated',
    SOCAILPROFILEURL_IS_SUCCESSFULLY_DELETED: 'socail profile url is successfully deleted',
    REQUEST_FOR_USER_DATA : 'Request for user data',
    ERROR_OCCURED_IN_GET_USER_INFO_FOR : 'Error occureed in get user info for ',
    WE_COULD_NOT_FOUND_AN_ACCOUNT_ASSOCIATED_WITH : 'We could not found an account associated with ',
    DATA_GET_SUCCESSFULLY : 'Data get successfully ',
  },

  AUTHENTICATION: {
    USER_AUTHENTICATION_STARTED:'User authentication started for user',
    USER_DETAILS_NOT_PROVIDED:'Invalid credential',
    USER_DETAIL_FOUND:'User details found for user',
    PROBLEM_OCCURED :'Problem occurred',
    INVALID_CREDENTIAL:'Invalid credentials',
    EMAIL_NOT_VERIFIED:'Email not verified',
    INVALID_USER_ID: `We couldn't find an account associated with `,
    MISSING_EXPECTED_INPUT : 'Expected input credential was not present',
    FORGOT_PASSWORD_REQUEST: 'Get forgot password request', 
    RESET_PASSWORD_REQUEST: 'Get reset password request', 
    SEND_VERIFICATION_MAIL_SUCCESSFULLY: 'Send verification mail successfully',
    INTERNAL_ERROR : 'Internal error occurred',
    RESET_PASSWORD_LINK_SEND_SUCCESSFULLY: 'Reset password link has been sent to your email. Please check your email',
    INVALID_PASSWORD_LENGTH: 'Your password must include at least 8 characters',
    PASSWORD_NOT_MATCHED: 'Your new password and confirm password do not match',
    PASSWORD_RESET_SUCCESSFULLY: 'Password reset successfully',
    INVALID_REQUEST: 'Invalid Request',
    INACTIVE_ACCOUNT: 'Your account is inactive. Please send a message to "contact@smartpathshala.com" to activate it',
    PLEASE_VERIFIED_YOUR_EMAIL_ID: 'It seems you have missed Email Verification, Please go to your inbox and verify your email or resend verification link',
    BAD_REQUEST: 'Bad request',
  },

  USER: {
    SEND_VERIFICATION_MAIL_FAIL: 'Send verification mail failed',
    MISSING_EXPECTED_INPUT : 'Expected input credential was not present',
    SEND_VERIFICATION_MAIL_SUCCESS: `Verification link sent on your registered email id. Please check inside Inbox and Spam folders. It may take few minutes to deliver it.`,
    REGISTER_SUCCESSFULLY: ' register successfully',
    GET_DATA_SUCCESSFULLY : 'data get successfully ',
    UPDATE_SUCCESSSFULLY : 'Data updated successfully',
    DELETED_SUCCESSFULLY: ' User data deleted successfully',
    GET_MAIL_VERIFICATION_REQUEST: 'Get email verification request',
    MAIL_VERIFICATION_SUCCESSSFULL: 'Email verification successful',
    INVALID_MAIL_VERIFICATION_TOKEN: 'Invalid email verification token',
    NEW_PASSWORD_FOR_USER : 'New password of user',
    INTERNAL_ERROR : 'Internal error occurred',
    FIll_ALL_BLANK_FIELD : 'Fill all blank filed',
    OLD_PASSWORD_IS_INCORRECT	: 'Old password is incorrect',
    FAIL_TO_UPDATE_PASSWORD: 'Fail to upadte password',
    PASSWORD_IS_SUCCESSFULLY_UPDATED_FOR : 'Password is successfully updated for ',
    PASSWORD_IS_SUCCESSFULLY_UPDATED : 'Password is successfully updated ',
    NEW_PASSWORD_AND_CONFIRM_PASSWORD_IS_MISMATCHED : ' New password and conform new password is mismatched ',
    VERIFICATION_MAIL_SEND_BUT_TOKEN_NOT_PROVIDED: 'Verification mail send but token not provided ',
    GREETING_MAIL_SEND_SUCCESSFULLY: 'Greeting mail send successfully',
    CHANGE_PASSWORD_MAIL_SEND_SUCCESSFULLY: 'Change password notification mail send successfully',
    WE_COULD_NOT_FOUND_AN_ACCOUNT_ASSOCIATED_WITH:'We could not find an account associated with',
    MAIL_SENDING_FAIL:'Sending verification mail failed, Please try later!',
    PERMISSION_DENIED: 'You have no permission to perform this action',
  },

  INSTRUCTOR : {
    REQUEST_FOR_INSTRUCTOR_DATA : 'Request for instructor data',
    ERROR_OCCURED_IN_GET_INSTRUCTOR_INFO_FOR :'Error occurred in  get instructor info for',
    INTERNAL_ERROR_OCCURED:'Internal error occurred',
    WE_COULD_NOT_FOUND_AN_ACCOUNT_ASSOCIATED_WITH:'We could not find an account associated with',
    DATA_GET_SUCCESSFULLY : 'Data get successfully',

    GET_OBJECT_AND_STORE_INSTRUCTOR :'Get object and store instructor',
    INSTRUCTOR_DATA_NOT_FOUND : 'Instructor data not found',
    INSTRUCTOR_SUCCESSFULLY_SAVED : 'Instrcutor successfully saved',
    FIll_ALL_BLANK_FIELD : 'Fill all blank filed',
    USER_ALREADY_REGISTERED: ' User already registered ',
    FAILED_TO_SAVE : 'Failed to save data ',
  },

  STUDENT: {
    REGISTRATION_REQUEST: 'Request for student registration ',
    STUDENT_SAVE_SUCCESSFULLY: 'Student data persisted successfully in student collection ',
    USER_SAVE_SUCCESSFULLY: 'Student data persisted successfully in user collection ',
    MISSING_EXPECTED_INPUT : 'Expected input was not present ',
    INTERNAL_ERROR : 'Internal error occurred ',
    COURSE_UPDATE_SUCCESSSFULLY : 'Course updated successfully ',
    GET_DATA_SUCCESSFULLY : 'data get successfully ',
    FAILED_TO_SAVE : 'Failed to save data ',
    SAVE_SUCCESSFULLY  : 'Save data successfully ',
    USER_ALREADY_REGISTERED: ' already registered ',
    DELETED_SUCCESSFULLY: ' Student data deleted successfully ',
    FAILED_TO_DELETE: ' Student data deleted successfully ',
    REQUEST_FOR_STUDENT_DATA:'Request for student data ',
    ERROR_OCCURED_IN_GET_STUDENT_INFO_FOR:'Error occurred in  get student info for ',
    DATA_GET_SUCCESSFULLY :'data get successfully ',
    NO_DATA_AVAILABLE: 'No data available ',
    WE_COULD_NOT_FOUND_AN_ACCOUNT_ASSOCIATED_WITH:'We could not find an account associated with ',
    WE_COULD_NOT_FOUND_ANY_CONTENT_ASSOCIATED_WITH:'We could not find any content associated with ',
    ASSIGN_COURSE_PERSISTED_IN_STUDENT: 'Assign course persisted in student collection successfully',
    COURSE_ALREADY_ASSIGN: 'Course already assign',
    SUBSCRIPTION_UPDATE_SUCCESSSFULLY : 'Student subscription detials updated successfully ',
    LEARNING_STATUS_SUCCESSFULLY_UPDATED:'Learning status is successfully updated ',
    STUDENT_STATUS_SUCCESSFULLY_UPDATED:'student status successfully updated',
    STUDENT_STATUS_NOT_UPDATED:'student status not updated',
    ASSIGN_COURSE_SUCCESSFULLY: 'Course assign successfully',
    COURSE_LEARNING_STATUS_UPDATED_SUCCESSFULLY: 'Course learning status updated successfully',
    PERMISSION_DENIED: 'You have no permission to perform this action',
    STUDENT_NOT_FOUND: 'Student not found',
    NO_ASSIGN_COURSE_FOUND: 'No assign course found',
    COURSE_VERSION_UPDATED_SUCCESSFULLY: 'Course version updated successfully',
    REASSIGN_COURSE_FROM_COURSE_HISTORY: 'Reassign, last course from history successfully',
    NO_VERSION_HISTORY_AVAILABLE_FOR_COURSE: 'No version history available for this course',
    COURSE_UP_TO_DATE: 'Your course alredy up to date',
    COURSE_ASSIGN_YOUTUBE_SUBSCRIPTION_ERROR: 'You need to subscribe youtube channel to assign this course.',
    COURSE_ASSIGN_ERROR: 'Problem occurred in assigning course.',
  },

  QUESTION: {
    MISSING_EXPECTED_INPUT : 'Expected input credential was not present',
    INTERNAL_ERROR : 'Internal error occurred',
    UPDATE_SUCCESSSFULLY : 'Data updated successfully',
    DATA_GET_SUCCESSFULLY : 'Data get successfully',
    FAILED_TO_SAVE : 'Failed to save data',
    SAVE_SUCCESSFULLY  : 'Save data successfully',
    NO_RIGHTS: 'You do not have enough rights to perform this operation',
    NO_DATA_FOUND: 'No question found',
  },

  ASSESSMENT: {
    MISSING_EXPECTED_INPUT : 'Expected input credential was not present',
    INTERNAL_ERROR : 'Internal error occurred',
    UPDATE_SUCCESSSFULLY : 'Data updated successfully',
    GET_DATA_SUCCESSFULLY : 'Data get successfully',
    FAILED_TO_SAVE : 'Failed to save data',
    SAVE_SUCCESSFULLY  : 'Save data successfully',
    NO_RIGHTS: 'You do not have enough rights to perform this operation',
    BAD_REQUEST: 'Bad request',
  },

  ASSESSMENT_RESULT: {
    MISSING_EXPECTED_INPUT : 'Expected input credential was not present',
    INTERNAL_ERROR : 'Internal error occurred',
    UPDATE_SUCCESSSFULLY : 'Data updated successfully',
    GET_DATA_SUCCESSFULLY : 'Data get successfully',
    FAILED_TO_SAVE : 'Failed to save data',
    SAVE_SUCCESSFULLY  : 'Save data successfully',
    ASSESSMENT_NOT_FOUND  : 'Assessment not found or questions not present in assessment',
    QUESTION_NOT_MATCH  : 'Take assessment question not match with assessment question',
    ASSESSMENT_NOT_FOUND_IN_ASSIGN_COURSE: 'Assessment not found in assign courses',
    NO_ASSIGN_COURSE_FOUND: 'No assign course found',
  },
  
  ASSIGN_COURSE: {
    ASSIGN_COURSE_SUCCESSFULLY: 'Course assign successfully',
    COURSE_ALREADY_ASSIGN: 'Course already assign',
    INTERNAL_ERROR : 'Internal error occurred',
    GET_DATA_SUCCESSFULLY : 'Data get successfully',
    MISSING_EXPECTED_INPUT : 'Expected input credential was not present',
    REQUEST_FOR_SET_STATUS_OF_LEARNING_DATA: 'Request for set status of learning data ',
    ERROR_OCCURED_IN_SET_STATUS_OF_LEARNING_DATA_FOR : 'Error occured in set status of learning data for ',
    NO_DATA_FOUND_FOR_THIS_COURSE_AND_STUDENT :'No data found for this course and student ',
    LEARNING_STATUS_SUCCESSFULLY_UPDATED:'Learning status is successfully updated ',
    NO_DATA_FOUND_FOR_UPDATE : 'No data found for update ',
    REQUEST_FOR_GET_ASSIGN_COURSES_OF_STUDENT : 'Request for get assign courses of student ',
    ERROR_OCCURED_TO_GET_ASSIGN_COURSE_FOR : 'Error occured to get assign courses for ',
    ASSIGN_COURSE_RATTED_SUCCESSFULLY : 'Assign course rating updated successfully',
    COURSE_RATTED_SUCCESSFULLY : 'Course rating updated successfully ',
  },

  SKILLS: {
    GET_OBJECT_AND_STORE_SKILL:'Skill data persistence started',
    GET_SKILL_STARTED:'Retrival of skills started',
    GET_SKILL_COMPLETED:'Retrival of skills completed',
    DELETE_SKILL_STARTED:'Deletion of skills started',
    DELETE_SKILL_STARTED:'Deletion of skills started',
    SKILL_DATA_NOT_FOUND : 'Skill not found',
    SKILL_SUCCESSFULLY_SAVED : 'Skill successfully saved',
    SKILL_SUCCESSFULLY_UPDATED : 'Skill successfully updated',
    SKILL_SUCCESSFULLY_DELETED : 'Skill successfully deleted',
    SKILL_NOT_SAVED : 'Skill not saved',
  },

  ADMIN : {
    REQUEST_FOR_ADMIN_DATA : 'Request for admin data',
    ERROR_OCCURED_IN_GET_ADMIN_INFO_FOR :'Error occurred in  get admin info for',
    INTERNAL_ERROR_OCCURED:'Internal error occurred',
    WE_COULD_NOT_FOUND_AN_ACCOUNT_ASSOCIATED_WITH:'We could not find an account associated with',
    DATA_GET_SUCCESSFULLY : 'Data get successfully',
  },

  PROJECTS: {
    GET_OBJECT_AND_STORE_PROJECT:'Project data persistence started',
    GET_PROJECT_STARTED:'Retrival of projects started',
    GET_PROJECT_COMPLETED:'Retrival of projects completed',
    DELETE_PROJECT_STARTED:'Deletion of projects started',
    DELETE_PROJECT_STARTED:'Deletion of projects started',
    PROJECT_DATA_NOT_FOUND : 'Project not found',
    PROJECT_SUCCESSFULLY_SAVED : 'Project successfully saved',
    PROJECT_SUCCESSFULLY_UPDATED : 'Project successfully updated',
    PROJECT_SUCCESSFULLY_DELETED : 'Project successfully deleted',
    PROJECT_NOT_SAVED : 'Project not saved',
    PROJECT_NOT_UPDATED : 'Project not updated',
    NO_RIGHTS_TO_UPDATE: 'You have no rights to modify',
    DRAFTED_REJECTED_UPDATED:'Only drafted or rejected project can be updated',
    PROJECT_STATUS_UPDATED_SUCCESSFULLY:'Project status successfully updated',
    GET_EPICS_SUCCESSFULLY:'Get epics successfully',
    EPICS_ADDED_SUCCESSFULLY:'Epics added successfully',
    EPICS_DATA_NOT_FOUND : 'Epic not found',
    EPICS_SUCCESSFULLY_SAVED : 'Epic successfully saved',
    EPICS_SUCCESSFULLY_UPDATED : 'Epic successfully updated',
    EPICS_SUCCESSFULLY_DELETED : 'Epic successfully deleted',
    EPICS_NOT_SAVED : 'Epic not saved',
    MISSING_EXPECTED_INPUT : 'Expected input credential was not present',
    INTERNAL_ERROR : 'Internal error occurred',
    No_EPICS_FOUND: 'No epic data found',
  },

  SKILLS: {
    GET_OBJECT_AND_STORE_SKILL:'Skill data persistence started',
    GET_SKILL_STARTED:'Retrival of skills started',
    GET_SKILL_COMPLETED:'Retrival of skills completed',
    DELETE_SKILL_STARTED:'Deletion of skills started',
    DELETE_SKILL_STARTED:'Deletion of skills started',
    SKILL_DATA_NOT_FOUND : 'Skill not found',
    SKILL_SUCCESSFULLY_SAVED : 'Skill successfully saved',
    SKILL_SUCCESSFULLY_UPDATED : 'Skill successfully updated',
    SKILL_SUCCESSFULLY_DELETED : 'Skill successfully deleted',
    SKILL_NOT_SAVED : 'Skill not saved',
  },

  ADMIN : {
    REQUEST_FOR_ADMIN_DATA : 'Request for admin data',
    ERROR_OCCURED_IN_GET_ADMIN_INFO_FOR :'Error occurred in  get admin info for',
    INTERNAL_ERROR_OCCURED:'Internal error occurred',
    WE_COULD_NOT_FOUND_AN_ACCOUNT_ASSOCIATED_WITH:'We could not find an account associated with',
    DATA_GET_SUCCESSFULLY : 'Data get successfully',
  },

  PROJECTS: {
    GET_OBJECT_AND_STORE_PROJECT:'Project data persistence started',
    GET_PROJECT_STARTED:'Retrival of projects started',
    GET_PROJECT_COMPLETED:'Retrival of projects completed',
    DELETE_PROJECT_STARTED:'Deletion of projects started',
    DELETE_PROJECT_STARTED:'Deletion of projects started',
    PROJECT_DATA_NOT_FOUND : 'Project not found',
    PROJECT_SUCCESSFULLY_SAVED : 'Project successfully saved',
    PROJECT_SUCCESSFULLY_UPDATED : 'Project successfully updated',
    PROJECT_SUCCESSFULLY_DELETED : 'Project successfully deleted',
    PROJECT_NOT_SAVED : 'Project not saved',
    PROJECT_NOT_UPDATED : 'Project not updated',

    GET_EPICS_SUCCESSFULLY:'Get epics successfully',
    EPICS_ADDED_SUCCESSFULLY:'Epics added successfully',
    EPICS_DATA_NOT_FOUND : 'Epic not found',
    EPICS_SUCCESSFULLY_SAVED : 'Epic successfully saved',
    EPICS_SUCCESSFULLY_UPDATED : 'Epic successfully updated',
    EPICS_SUCCESSFULLY_DELETED : 'Epic successfully deleted',
    EPICS_NOT_SAVED : 'Epic not saved',
    MISSING_EXPECTED_INPUT : 'Expected input credential was not present',
    INTERNAL_ERROR : 'Internal error occurred',
    No_EPICS_FOUND: 'No epic data found',

    GET_STORY_SUCCESSFULLY: 'Get story successfully',
    STORY_ADDED_SUCCESSFULLY:'Story added successfully',
    STORY_SUCCESSFULLY_UPDATED : 'Story successfully updated',
    STORY_SUCCESSFULLY_DELETED : 'Story successfully deleted',
    STORY_DATA_NOT_FOUND : 'Story not found',

    GET_TASK_SUCCESSFULLY: 'Get task successfully',
    TASK_ADDED_SUCCESSFULLY:'Task added successfully',
    TASK_SUCCESSFULLY_UPDATED : 'Task successfully updated',
    TASK_SUCCESSFULLY_DELETED : 'Task successfully deleted',
    TASK_DATA_NOT_FOUND : 'Task not found',

    STORY_DURATION_NOT_UPDATED: 'Story duration not updated',
    STORY_DURATION_UPDATED: 'Story duration updated',

    COURSE_DURATION_NOT_UPDATED: 'Course duration not updated',
    COURSE_DURATION_UPDATED: 'Course duration updated',
  },

  HELPS: {
    GET_OBJECT_AND_STORE_HELP:'Help data persistence started',
    HELP_DATA_NOT_FOUND : 'Help not found',
    HELP_SUCCESSFULLY_SAVED : 'Help successfully saved',
    HELP_NOT_SAVED : 'Help not saved',
    HELP_DATA_NOT_FOUND : 'Help not found',
    GET_HELP_STARTED:'Retrival of help started',
    GET_HELP_COMPLETED:'Retrival of help completed',
    HELP_SUCCESSFULLY_UPDATED : 'Help successfully updated',
    HELP_NOT_UPDATED : 'Help not updated',
  },

  CARTS: {
    GET_OBJECT_AND_STORE_CART:'Cart data persistence started',
    GET_CART_STARTED:'Retrival of carts started',
    GET_CART_COMPLETED:'Retrival of carts completed',
    CART_DATA_NOT_FOUND : 'Cart not found',
    CART_SUCCESSFULLY_SAVED : 'Cart successfully saved',
    CART_SUCCESSFULLY_UPDATED : 'Cart successfully updated',
    CART_NOT_SAVED : 'Cart not saved',
  },

  ORDERS: {
    GET_OBJECT_AND_STORE_ORDER:'Order data persistence started',
    GET_ORDER_STARTED:'Retrival of orders started',
    GET_ORDER_COMPLETED:'Retrival of orders completed',
    ORDER_DATA_NOT_FOUND : 'Order not found',
    ORDER_SUCCESSFULLY_SAVED : 'Order successfully saved',
    ORDER_SUCCESSFULLY_UPDATED : 'Order successfully updated',
    ORDER_NOT_SAVED : 'Order not saved',
    ORDER_NOT_UPDATED : 'Order not updated',
    TXNAMOUNT_NOT_MATCHED: appConstants.TXNAMOUNT_NOT_MATCHED,
    TXNAMOUNT_NOT_VERIFIED: appConstants.TXNAMOUNT_NOT_VERIFIED,
  },
}
